### ISSUE TITLE
2017-11-17 目标

### ISSUE THREAD

**Issue by wubaiqing** [yuanmin564/Test#1]
- [x] 在 Github - [Issues](https://github.com/yuanmin564/Test/issues) 中提出遇到的问题。
- [x] 了解什么是 [Markdown](https://guides.github.com/features/mastering-markdown/)

### 举例
问题描述用`中/英`都可以，不要像它混合用：https://github.com/ant-design/ant-design/issues/8020

**Comment by yuanmin564** [comment]
11月20日学习内容
=============

一、Markdown简介
---------------
      用标记语法代替普通的排版格式，适用于经常需要排版，而且可以提高编程效率的一款语言。


二、常见语法
---------------
      1.段落：一个以上的空行，两行即可表示一个段落
      2.标题：‘#’数量对应标题级别，1个#对应一级标题，以此类推，共六级
      3.引用：引用文字前加‘>’，即可显示引用
      4.无序列表： ‘*1’、‘+1’、‘-1’即可显示为‘·1’
      5.有序列表：‘⒈1’即可显示为‘⒈1’
      6.代码段：用‘’标记代码即可完全显示代码段，而 &、< 和 > 也一样会自动转成 HTML 实体；要建立一个已经格式化好的代码区块，只要每行都缩进 4 个空格或是一个 tab 就可以了。
      7.链接：This is an [example link](http://example.com/)   为‘example link’这部分文字插上一个‘http://example.com/’的链接
      8.图片：![]()，语法和链接很类似，[]内为图片的说明文字，()内为图片的链接
      9.分割线：三个*即可形成一条分割线

**Comment by wubaiqing** [comment]
@yuanmin564 回复就要用 `markdown`。

**Comment by wubaiqing** [comment]
@yuanmin564 Issuse 学完了吗？学完需要关闭！

**Comment by yuanmin564** [comment]
A First Level Header
====================
A Second Level Header
---------------------

Now is the time for all good men to come to
the aid of their country. This is just a
regular paragraph.

The quick brown fox jumped over the lazy
dog's back.
### Header 3

> This is a blockquote.
> 
> This is the second paragraph in the blockquote.
>
> ## This is an H2 in a blockquote
